# Dockerfile.sklearn
FROM python:3.9-slim

WORKDIR /app

# Installation des dépendances nécessaires
RUN pip install --no-cache-dir pandas scikit-learn joblib

# Copie du script d'évaluation
COPY evaluate.py /app/evaluate.py

# Commande par défaut
CMD ["python", "evaluate.py"]
