"""le truc de davy

Revision ID: b4fcb140f321
Revises: a120c7fe4167
Create Date: 2026-02-28 00:30:39.712682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b4fcb140f321'
down_revision = 'a120c7fe4167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition_announcements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('competition_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competition_organizers',
    sa.Column('competition_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('competition_id', 'user_id')
    )
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Enum('DRAFT', 'UPCOMING', 'ACTIVE', 'CLOSED', 'FINISHED', 'ARCHIVED', name='competitionstatus', native_enum=False), nullable=False))
        batch_op.add_column(sa.Column('task_type', sa.Enum('CLASSIFICATION', 'REGRESSION', 'CLUSTERING', 'NLP', 'COMPUTER_VISION', name='tasktype', native_enum=False), nullable=False))
        batch_op.add_column(sa.Column('problem_statement', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rules', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('data_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('evaluation_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('prizes', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('faq', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('banner_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('registration_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('results_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('primary_metric', sa.Enum('ACCURACY', 'F1_SCORE', 'PRECISION', 'RECALL', 'AUC_ROC', 'LOG_LOSS', 'RMSE', 'MAE', 'R2', 'MAPE', name='metricname', native_enum=False), nullable=False))
        batch_op.add_column(sa.Column('secondary_metrics', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('evaluation_config', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('max_submissions_per_day', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('max_submissions_total', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('max_file_size_mb', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('execution_timeout_seconds', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('allowed_formats', postgresql.JSON(astext_type=sa.Text()), nullable=False))
        batch_op.add_column(sa.Column('train_dataset_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('train_dataset_path', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('test_dataset_path', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('sample_submission_url', sa.String(length=512), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_competitions_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_competitions_status'), ['status'], unique=False)
        batch_op.drop_constraint(batch_op.f('competitions_created_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('processed_dataset_path')
        batch_op.drop_column('name')
        batch_op.drop_column('raw_dataset_path')
        batch_op.drop_column('evaluation_metric')

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('model_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=15),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('model_type',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evaluation_metric', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('raw_dataset_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Le nom de la compétition'))
        batch_op.add_column(sa.Column('processed_dataset_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('competitions_created_by_fkey'), 'users', ['created_by'], ['id'])
        batch_op.drop_index(batch_op.f('ix_competitions_status'))
        batch_op.drop_index(batch_op.f('ix_competitions_slug'))
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('sample_submission_url')
        batch_op.drop_column('test_dataset_path')
        batch_op.drop_column('train_dataset_path')
        batch_op.drop_column('train_dataset_url')
        batch_op.drop_column('allowed_formats')
        batch_op.drop_column('execution_timeout_seconds')
        batch_op.drop_column('max_file_size_mb')
        batch_op.drop_column('max_submissions_total')
        batch_op.drop_column('max_submissions_per_day')
        batch_op.drop_column('evaluation_config')
        batch_op.drop_column('secondary_metrics')
        batch_op.drop_column('primary_metric')
        batch_op.drop_column('results_date')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('registration_start')
        batch_op.drop_column('banner_url')
        batch_op.drop_column('faq')
        batch_op.drop_column('prizes')
        batch_op.drop_column('evaluation_description')
        batch_op.drop_column('data_description')
        batch_op.drop_column('rules')
        batch_op.drop_column('problem_statement')
        batch_op.drop_column('task_type')
        batch_op.drop_column('status')
        batch_op.drop_column('title')
        batch_op.drop_column('slug')

    op.drop_table('competition_organizers')
    op.drop_table('competition_announcements')
    # ### end Alembic commands ###
