"""Ajout de la table participation

Revision ID: d3fc6783963f
Revises: 2c84c3f5e1fc
Create Date: 2026-02-20 23:41:10.034598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3fc6783963f'
down_revision = '2c84c3f5e1fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participations_competitions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('competition_id', sa.UUID(), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'competition_id')
    )
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_dataset_path', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('processed_dataset_path', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('evaluation_metric', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.drop_column('evaluation_metric')
        batch_op.drop_column('processed_dataset_path')
        batch_op.drop_column('raw_dataset_path')

    op.drop_table('participations_competitions')
    # ### end Alembic commands ###
